### ISSUE TITLE
Bug: Broken links on LPA overview page

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#419]
**What were you expecting to see:**

A summary of issues related to a dataset

**What are you seeing:**

![Image](https://github.com/user-attachments/assets/84b0578e-eb72-44ff-bb2f-2184f1a8d5d8)

**Who raised it**
MJ

**Problem causing**
LPAs, such as [North Lincolnshire Council](https://submit.planning.data.gov.uk/organisations/local-authority:NLN) are unable to review issues related to their dataset

Steps to replicate:
- Access [North Lincolnshire Council overview page](https://submit.planning.data.gov.uk/organisations/local-authority:NLN)
- Try and select their Tree dataset

Tasks:

- [ ] Investigate why this occurs
- [ ]

**Comment by MJFaucherFolie** [comment]
A brief investigation highlights that this is only impacting North Lincs.

**Comment by DilwoarH** [comment]
Error that's happening:

```
{
  "errorMessage": "Unknown issue type: future entry-date",
  "errorStack": "Error: Unknown issue type: future entry-date\n    at Object.getTaskMessage (__REDACTED__/submit/src/services/performanceDbApi.js:213:13)\n    at __REDACTED__/submit/src/controllers/OrganisationsController.js:604:36\n    at Array.map (<anonymous>)\n    at Object.getDatasetTaskList (__REDACTED__/submit/src/controllers/OrganisationsController.js:601:31)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async conditionalTaskListHandler (__REDACTED__/submit/src/controllers/OrganisationsController.js:670:16)",
  "level": "warn",
  "message": "getDatasetTaskList() failed for lpa='local-authority:NLN', datasetId='tree'",
  "service": "lpa-data-validation-frontend",
  "timestamp": "2024-09-12T11:55:22.816Z",
  "type": "App"
}
```
